# -*- coding: utf-8 -*-
"""PMC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3YWYVTAjy0UyKV8SEZwkvS7k6lkfym7
"""

import re
import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime
from urllib.parse import urljoin

ARTICLE_URL = "https://pmc.ncbi.nlm.nih.gov/articles/PMC11786524/"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": ARTICLE_URL
}

!pip install pandas requests beautifulsoup4 lxml

import requests

PMCID_NUM = "11786524"  # from PMCID: PMC11786524
OAI_URL = "https://pmc.ncbi.nlm.nih.gov/api/oai/v1/mh/"
params = {
    "verb": "GetRecord",
    "identifier": f"oai:pubmedcentral.nih.gov:{PMCID_NUM}",
    "metadataPrefix": "pmc"   # full-text XML
}

r = requests.get(OAI_URL, params=params, timeout=30)
r.raise_for_status()

xml_text = r.text
xml_text[:500]

import pandas as pd
from bs4 import BeautifulSoup

soup = BeautifulSoup(xml_text, "xml")

table_wraps = soup.find_all("table-wrap")
len(table_wraps)

import re
from datetime import datetime

def safe_name(s):
    s = (s or "").strip().lower()
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return s[:60] if s else "table"

tables = []
ts = datetime.now().strftime("%Y%m%d_%H%M")

for i, tw in enumerate(table_wraps, start=1):
    label = tw.find("label")
    caption = tw.find("caption")
    table = tw.find("table")

    label_text = label.get_text(" ", strip=True) if label else f"Table_{i}"
    caption_text = caption.get_text(" ", strip=True) if caption else ""

    if not table:
        print(f"{label_text}: no <table> found")
        continue

    # pandas can often read this directly because JATS tables use HTML-like tags
    try:
        df = pd.read_html(str(table))[0]
    except ValueError:
        print(f"{label_text}: pandas could not read table")
        continue

    # light cleanup
    df.columns = [str(c).replace("\n", " ").strip() for c in df.columns]
    df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

    filename = f"{safe_name(label_text)}_{ts}.csv"
    df.to_csv(filename, index=False)

    tables.append((label_text, caption_text, df))
    print("Saved:", filename)

len(tables)

for label_text, caption_text, df in tables:
    print("\n", label_text)
    print("Caption:", caption_text[:160], "...")
    display(df.head())

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

def to_numeric_series(s: pd.Series) -> pd.Series:
    """
    Convert messy numeric-looking strings to floats:
    - removes commas
    - removes percent signs
    - removes footnotes like 'a' or symbols
    - keeps digits, dot, minus
    """
    if s.dtype != "object":
        return pd.to_numeric(s, errors="coerce")

    cleaned = (
        s.astype(str)
         .str.replace(",", "", regex=False)
         .str.replace("%", "", regex=False)
         .str.replace(r"[^0-9\.\-]+", "", regex=True)
    )
    return pd.to_numeric(cleaned, errors="coerce")

def get_numeric_columns(df: pd.DataFrame, min_nonnull_ratio: float = 0.5):
    """
    Try converting object columns to numeric and return columns that
    look mostly numeric.
    """
    numeric_cols = []
    converted = {}

    for col in df.columns:
        ser = to_numeric_series(df[col])
        nonnull_ratio = ser.notna().mean()
        if nonnull_ratio >= min_nonnull_ratio:
            numeric_cols.append(col)
            converted[col] = ser

    return numeric_cols, converted

def plot_numeric_histograms(label: str, df: pd.DataFrame, max_cols: int = 2):
    num_cols, converted = get_numeric_columns(df)

    if not num_cols:
        print(f"[{label}] No numeric columns detected to plot histograms.")
        return

    for col in num_cols[:max_cols]:
        plt.figure()
        converted[col].dropna().plot(kind="hist", bins=20)
        plt.title(f"{label} — Distribution of {col}")
        plt.xlabel(col)
        plt.ylabel("Count")
        plt.show()

def plot_top_categories_bar(label: str, df: pd.DataFrame, category_col: str = None, value_col: str = None, top_n: int = 10):
    """
    Bar chart of top categories by a numeric value. If you don't pass columns,
    it tries to pick reasonable defaults:
    - category_col: first object column
    - value_col: first numeric-ish column
    """
    df2 = df.copy()

    # pick category col
    if category_col is None:
        obj_cols = [c for c in df2.columns if df2[c].dtype == "object"]
        if not obj_cols:
            print(f"[{label}] No text/category columns detected.")
            return
        category_col = obj_cols[0]

    # pick value col
    if value_col is None:
        num_cols, converted = get_numeric_columns(df2)
        if not num_cols:
            print(f"[{label}] No numeric columns detected for bar plot.")
            return
        value_col = num_cols[0]
        df2[value_col] = converted[value_col]
    else:
        df2[value_col] = to_numeric_series(df2[value_col])

    df2 = df2.dropna(subset=[category_col, value_col])

    grouped = (
        df2.groupby(category_col, as_index=False)[value_col]
           .sum()
           .sort_values(value_col, ascending=False)
           .head(top_n)
    )

    plt.figure()
    plt.bar(grouped[category_col].astype(str), grouped[value_col])
    plt.title(f"{label} — Top {top_n} {category_col} by {value_col}")
    plt.xlabel(category_col)
    plt.ylabel(value_col)
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()

def plot_table_missingness(label: str, df: pd.DataFrame):
    """
    Visualize missing values per column.
    """
    missing = df.isna().sum().sort_values(ascending=False)
    if missing.sum() == 0:
        print(f"[{label}] No missing values.")
        return

    plt.figure()
    plt.bar(missing.index.astype(str), missing.values)
    plt.title(f"{label} — Missing values by column")
    plt.xlabel("Column")
    plt.ylabel("Missing count")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()

for label, caption, df in tables:
    print("\n" + "="*80)
    print(label)
    print("Caption:", (caption[:200] + "...") if len(caption) > 200 else caption)

    plot_table_missingness(label, df)
    plot_numeric_histograms(label, df, max_cols=2)
    plot_top_categories_bar(label, df, top_n=10)